secrets:
  artifactory_password:
      path: /secret/shared/tap/drone-secrets/ARTIFACTORY_SVCPEJKN001_BINREPO

pipeline:
  build:
    image: python:2.7
    commands:
      - apt-get update
      - apt-get install curl build-essential git libffi-dev libssl-dev default-libmysqlclient-dev libpython-dev python-pip python-dev unzip wget -y
      - pip install -r requirements.txt
      - python ./setup.py install
      - python ./setup.py sdist
    when:
      branch: [ master ]
      event: push

  python-publish:
    secrets: [ artifactory_password ]
    image: cpe.docker.target.com/drone-python-publish:latest
    repository: https://binrepo.target.com/artifactory/api/pypi/cpe-pypi/forseti
    username: svcpejkn001
    password: ${ARTIFACTORY_PASSWORD}
    when:
      branch: [ master ]
      event: push
